### ISSUE TITLE
Fenster implementieren

### ISSUE THREAD

**Issue by errorsHurt** [errorsHurt/PotentialFractal#9]
Es soll ein Fenster erstellt werden das durchgehen bis schließen der Anwendung offen gehalten wird

Das Fenster braucht:

- Menüpunkte:
 - File
 - Edit

Beispiel Code zum erstellen eine Fensters:
from tkinter import *
# Erzeugung des Fensters
tkFenster = Tk()
tkFenster.title('Test')
# Aktivierung des Fensters
tkFenster.mainloop()

**Comment by thexwon** [comment]
PyQT5
